### ISSUE TITLE
Dimension of variable `dates` in input dara file

### ISSUE THREAD

**Issue by ctroupin** [gher-uliege/DINCAE.jl#10]
If I understand well the doc at https://github.com/gher-uliege/DINCAE.jl/blob/ef26b38303d2a7b994bb6faba7ff850ba4e17ee2/src/points.jl#L492-L508
the variable `size`, with dimension `track`, indicates the number of observations in each track (altimetry).

But then `dates`  is defined as the _time instance of the gridded field_ and has also `track` as a dimension.

It's not clear to me why it's the case, i.e. why the time instances of the gridded field should correspond to the tracks?
On a given day there are several tracks?

**Comment by Alexander-Barth** [comment]
`dates(track)` essentially records to which time instance of the gridded field a particular track corresponds to.

Here are the number of the altimetry test case: 9628 time instance of the gridded field

Load the data:
```
julia> values = NCDatasets.loadragged(ds["sla"],:);

julia> typeof(values)
Vector{SubArray{Float32, 1, Vector{Float32}, Tuple{UnitRange{Int64}}, true}} (alias for Array{SubArray{Float32, 1, Array{Float32, 1}, Tuple{UnitRange{Int64}}, true}, 1})

julia> length(values)
9628

julia> length.(values)[1:10]
10-element Vector{Int64}:
 301
 491
 644
[...]
```

`length(values)` is the number of time instance (for the gridded field) and `length.(values)` the number of values at a particular time instance. 

Maybe it is better to discuss this off-line?

**Comment by ctroupin** [comment]
OK now clear: 
- the observations are sorted by time
- the variable `dates` will store the time where we want the analysis (12 months for ex) 
- the number of observations for each time instance will be stored as well.
