### ISSUE TITLE
Flux.jl and CUDA.jl not automatically installed. 

### ISSUE THREAD

**Issue by ctroupin** [gher-uliege/DINCAE.jl#17]
In the doc it is mentioned that
> DINCAE.jl depends on Flux.jl and CUDA.jl which will automatically be installed. 

However if we follow the instructions:
```julia
using Pkg
Pkg.add(url="https://github.com/gher-uliege/DINCAE.jl", rev="main")
Pkg.add(url="https://github.com/gher-uliege/DINCAE_utils.jl", rev="main")
```
neither `Flux` nor `CUDA` is installed.

```julia
(MyProject) pkg> st
Status `~/MyProject/Project.toml`
  [0d879ee6] DINCAE v2.0.2 `https://github.com/gher-uliege/DINCAE.jl#main`
  [f57bf84d] DINCAE_utils v0.1.0 `https://github.com/gher-uliege/DINCAE_utils.jl#main`
```
Also `cuDNN` has to be installed.
```julia
julia> using DINCAE
┌ Warning: Package cuDNN not found in current path.
│ - Run `import Pkg; Pkg.add("cuDNN")` to install the cuDNN package, then restart julia.
│ - If cuDNN is not installed, some Flux functionalities will not be available when running on the GPU.
└ @ FluxCUDAExt ~/.julia/packages/Flux/u7QSl/ext/FluxCUDAExt/FluxCUDAExt.jl:56
```

Shall we remove that from the doc, or rephrase it?

**Comment by Alexander-Barth** [comment]
Well it is installed in `~/.julia/packages` but not per default available in your environment. The user does not need to explicitly install Flux to use DINCAE. How can we rephrase it that is does not lead to confusion? In any case we can mention the cuDNN issue (maybe expanding this https://github.com/gher-uliege/DINCAE.jl/blob/main/docs/src/index.md?plain=1#L51)

**Comment by ctroupin** [comment]
thanks, I see, the README is certainly clear enough, I was confused by the fact that CUDA was installed and available with `using CUDA` while Flux was installed but not available with `using Flux`.

We can add this to the doc at https://github.com/gher-uliege/DINCAE.jl/blob/main/docs/src/index.md?plain=1#L51:

A warning will be issued if `cuDNN` has not been installed installed:
```julia-repl
julia> using DINCAE
┌ Warning: Package cuDNN not found in current path.
│ - Run `import Pkg; Pkg.add("cuDNN")` to install the cuDNN package, then restart julia.
│ - If cuDNN is not installed, some Flux functionalities will not be available when running on the GPU.
```

**Comment by Alexander-Barth** [comment]
what about this updated section ?
https://github.com/gher-uliege/DINCAE.jl/blob/3a73aceae1944745fb116b621a5f005bd023b4fd/docs/src/index.md#L51

**Comment by ctroupin** [comment]
great, thanks!

**Comment by Alexander-Barth** [comment]
For the record, I just also made some other changes to the README

**Comment by ctroupin** [comment]
OK, I see it and it looks clearer to me!
