### ISSUE TITLE
DINCAE_utils.addcvpoint error

### ISSUE THREAD

**Issue by FranckzGithub** [gher-uliege/DINCAE.jl#22]
Hello, I already tested successfully the tutorial, but when i tried my own data i found this error when i run: "DINCAE_utils.addcvpoint(fname,varname; mincvfrac = 0.05);" do you have any idea about it? 

>>DINCAE_utils.addcvpoint(fname,varname; mincvfrac = 0.05);
ERROR: IOError: sendfile: Unknown system error -954851718 (Unknown system error -954851718)
Stacktrace:
 [1] uv_error
   @ .\libuv.jl:100 [inlined]
 [2] sendfile(dst::Base.Filesystem.File, src::Base.Filesystem.File, src_offset::Int64, bytes::Int64)
   @ Base.Filesystem .\filesystem.jl:153
 [3] sendfile(src::String, dst::String)
   @ Base.Filesystem .\file.jl:998
 [4] cp(src::String, dst::String; force::Bool, follow_symlinks::Bool)
   @ Base.Filesystem .\file.jl:384
 [5] cp
   @ .\file.jl:376 [inlined]
 [6] #addcvpoint#5
   @ C:\Users\Zhou laoshi\.julia\packages\DINCAE_utils\f4oUy\src\data.jl:101 [inlined]
 [7] top-level scope
   @ REPL[145]:1
 [8] top-level scope
   @ C:\Users\Zhou laoshi\.julia\packages\CUDA\35NC6\src\initialization.jl:190

**Comment by Alexander-Barth** [comment]
Could be this issue?

https://github.com/JuliaLang/julia/issues/30723

Does the issue persists when you rerun this function?

**Comment by FranckzGithub** [comment]
thank is working... but may you help me to select the optimal parameters to run the model, my dataset looks like this, i have 1970 layers, but when  i use this parameters:

epochs = 1000
batch_size = 32
enc_nfilter_internal = round.(Int,32 * 2 .^ (0:4))
clip_grad = 5.0
regularization_L2_beta = 0
ntime_win = 3
upsampling_method = :nearest
loss_weights_refine = (0.3,0.7)
save_epochs = 200:10:epochs

the results are very strange, and when i reduce the dataset, the results looks like better.... may you help me to select better those parameters? or any advice?, i have been trying to do this for a few weeks... many thanks in advance 
![PLOT_COMPARISSON OF READINGS](https://github.com/gher-uliege/DINCAE.jl/assets/115663434/d40da34d-cd3d-4b31-ae0e-f4ec3462bc87)

**Comment by Alexander-Barth** [comment]
Likely a windows issue unrelated to DINCAE.
