### ISSUE TITLE
First obs_err_std is always equal to 1f0

### ISSUE THREAD

**Issue by EhsanMehdipour** [gher-uliege/DINCAE.jl#26]
Hi Alex,

https://github.com/gher-uliege/DINCAE.jl/blob/cec71e4df59d1db6e9553a8c34d18251d55f6108/src/data.jl#L92

This line should change to:

```julia
        d[1].filename,d[1].varname,d[1].errvarname,
        obs_err_std = d[1].obs_err_std);
```
in case there is no errvarname.

Cheers,
Ehsan

**Comment by Alexander-Barth** [comment]
Yes, you are right, thanks!!
